config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # a guest can create a user, a user can see his profile and dashboard
  resources :users, only: [:show] do
    member do
      get 'dashboard'
    end
  end
  # all 7 crud action can be done for dogs.
  resources :dogs do
    # a guest can preview a specific dog page before login-in
    member do
      get 'preview'
    end
    # a user can create a new booking
    resources :bookings, only: [:new, :create]
    # can create a review
    resources :reviews, only: [:new, :create]
  end
  # a user can see details of one booking and delete.
  resources :bookings, only: [:show, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/dog.rb
class Dog < ApplicationRecord
  include PgSearch

  validates :name, presence: true
  validates :race, presence: true
  validates :size, presence: true, inclusion: { in: %w(small medium large),
    message: "%{value} is not a valid size" }
  validates :address, presence: true
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  belongs_to :owner, class_name: 'User'

  mount_uploader :photo, PhotoUploader

  pg_search_scope :search_dog_scope,
                  against: [:name, :race, :size, :description],
                  associated_against: {
                    user: [:name, :lastname]
                  },
                  using: {
                    tsearch: { prefix: true }
                  }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  # def self.average_rating(dog)
  #   # replace the dog with an array of his reviews
  #   array = dog.reviews
  #   # replace each review object by the rating integer
  #   rating_array = array.map(&:rating)
  #   # compute the average
  #   length = array.length
  #   average = rating_array.sum.to_f / length
  #   # return the average rating float
  #   return average.round(2)
  # end
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:preview, :index]
  before_action :set_user, only: [:new, :create]
  before_action :set_dog, only: [:show, :edit, :update, :destroy, :preview]

  def preview
    # give the bookings of the dog as an array to the views
    @bookings = @dog.bookings

    # give the user instance of the owner of the dog to the views
    @owner = @dog.owner

    # give the reviews as an array to the views
    @reviews = @dog.reviews

    # give the user who created the review as an array with index associated to @reviews
    @authors = @reviews.map(&:user)

    # give the average rating of the dog as an integer
    # @stars = Dog.average_rating(@dog)
    @stars = @dog.reviews.average(:rating)
  end

  def show
    # give the bookings of the dog as an array to the views
    @bookings = @dog.bookings

    # give the use instance of the owner of the dog to the views
    @owner = @dog.owner
    @markers = [{
        lat: @dog.latitude,
        lng: @dog.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { dog: @dog }),
        image_url: helpers.asset_url('/images/doge.png')
      }]

    # give the reviews as an array to the views
    @reviews = @dog.reviews

    # give the user who created the review as an array with index associated to @reviews
    @authors = @reviews.map(&:user)

    # give the average rating of the dog as an integer
    # @stars = Dog.average_rating(@dog)
    @stars = @dog.reviews.average(:rating)
  end

  def index

    if params[:query].present?
      search = Dog.search_dog_scope(params[:query])
      @dogs = search
    else
      @dogs = Dog.all # returns all dogs with coordinates
    end

    @markers = @dogs.map do |dog|
      {
        lat: dog.latitude,
        lng: dog.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { dog: dog }),
        image_url: helpers.asset_url('doge.png')
      }
    end
    # return array of all the dogs in the DB
    # @dogs = policy_scope(Dog.includes(:user))
    # give the average rating of the dog as an integer
    # @stars = @dogs.map { |dog| Dog.average_rating(dog) }
    @stars = @dogs.map { |dog| dog.reviews.average(:rating) }
    # @dogs = Dog.all
  end

  def new
    # pass a new dog empty dog instance to the view
    @dog = Dog.new
    authorize @dog
  end

  def create
    # create the dog with the params from the form
    @dog = Dog.new(dog_params)
    # @dog.photo = "/images/index.png" if @dog.photo.nil?

    authorize @dog
    # find the owner of the dog from the params of the form
    @user = current_user
    # set the owner to the dog
    @dog.owner = @user
    current_user.owner = true
    current_user.save!
    # redirects to the show page of the dog if the create is successfull otherwise render new form
    if @dog.save
      redirect_to dog_path(@dog)
    else
      render :new
    end
  end

  def edit
  end

  def update
    # goes to show page of the dog if update is successfull.
    if @dog.update(dog_params)
      redirect_to dog_path(@dog)
    else
      render :edit
    end
  end

  def destroy
    @user = @dog.owner
    @dog.destroy

    redirect_to user_path(@user)
  end

  private

  def set_dog
    # give the dog instance to the view
    @dog = Dog.find(params[:id])
    authorize @dog
  end

  def set_user
    # give the owner instance to the view
    @user = current_user
  end

  def dog_params
    params.require(:dog).permit(:name, :race, :address, :size, :description, :available, :photo, :owner_id)
  end
end

app/views/dogs/_info_window.html.erb
<h2><%= dog.name %></h2>
<p><%= dog.address %></p

app/views/dogs/edit.html.erb
  <%= simple_form_for(@dog) do |f| %>
    <%= f.error_notification %>


  <div class="form-inputs">
    <%= f.input :name,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "name" }%>
    <%= f.input :address,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "address" }%>
    <%= f.input :description,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "description" }%>
    <%= f.input :race,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "race" }%>
    <%= f.input :size,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "size" }%>
    <%= f.input :available,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "available" }%>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>

  </div>

  <div class="form-actions">
    <%= f.button :submit, "Update Dog", class: "btd-yel" %>
  </div>

<% end %>

app/views/dogs/index.html.erb
<div class="container">

   <br><h1>All Doggies</h1>
    <%= form_tag dogs_path, method: :get do %>
    <div class="search-form-control form-group">
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a dog"
    %>
    <%= submit_tag "Search", class: "btn btd-yels" %>
    </div>
    <% end %>

    <br />
  <div class="index">
    <div class="index-dog">
      <div class="cardsf">
          <% @dogs.each_with_index do |dog, i| %>
            <div class="card-dog">
              <%= cl_image_tag dog.photo, height: 200, width: 250, crop: :fill %>


                <% if @stars[i] %>
                  <% @stars[i].round(0).to_i.times do %>
                    <i class="fas fa-star"></i>
                  <% end %>
                <% end %>

                <% if current_user %>
                  <%= link_to dog.name.upcase, dog_path(dog), class: "links-sessions" %>
                <% else %>
                  <%= link_to dog.name.upcase, preview_dog_path(dog), class: "links-sessions" %>
                <%end%>
                <% if current_user %>
                  <% if policy(dog).edit? %>
                    <br><%= link_to "EDIT", edit_dog_path(dog), class:"btd-yels"  %>
                  <% end %>
                  <% if policy(dog).destroy? %>
                    <%= link_to "REMOVE", dog_path(dog),
                      method: :delete,
                      data: { confirm: "Are you sure you want to delete this dog?" }, class:"btd-yels" %>
                  <% end %>
                <% end %>
            <br><br></div>
          <% end %>
      </div>
    </div>

    <div class="find">

<!--       <br><h1>Find a Doggie near you !</h1> -->

      <div
      id="map"
      style="width: 100%;
      height: 100%;"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
    ></div>

    </div>

  </div>
</div>

app/views/dogs/new.html.erb
<div class="card-login">
  <h2>ADD <br> A DOGGIE</h2>
  <%= simple_form_for(@dog) do |f| %>
    <%= f.error_notification %>


  <div class="form-inputs">
    <%= f.input :name,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "name" }%>

    <%= f.input :address,
                required: true,
                autofocus: true,
                id: 'dog_address',
                input_html: { autocomplete: "address" }%>

    <%= f.input :description,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "description" }%>

    <%= f.input :race,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "race" }%>

    <%= f.input :size,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "size" }%>

    <%= f.input :available,
                required: true,
                autofocus: true,
                input_html: { autocomplete: "available" }%>

    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>

  </div>

  <div class="form-actions">
    <%= f.button :submit, "Add Dog", class: "btd-yel" %>
  </div>
<% end %>
  </div>

app/views/dogs/preview.html.erb
<div class="container">
  <div class="preview">

    <br><h1><%=@dog.name.capitalize%>
          <% if @stars %>
            <% @stars.round(0).to_i.times do %>
              <i class="fas fa-star"></i>
            <% end %>
          <% end %>
    </h1>


    <div class="card-show">
        <%= cl_image_tag @dog.photo, width: 200, height: 150, crop: :fill %>

        <br>
         <div class="fullspace">
           <%= link_to "BOOK #{@dog.name.upcase}", new_dog_booking_path(@dog), class: "btd-yel-lg" %>
         </div>
        <div class= "profile-grid">

          <div class= "description">
            <h3>Breed:</h3>
            <p><%= @dog[:race] %></p>
            <h3>Size:</h3>
            <p><%= @dog[:size] %></p>
            <h3>Description:</h3>
            <p><%= @dog[:description] %></p>
          </div>

          <div class= "dog-owner">
            <h3>Owner:</h3>
            <p><%= @owner[:name] %> <%= @owner[:lastname] %></p>
            <h3>Contact:</h3>
            <p><%= @owner[:email] %></p>
          </div>

        </div>

    </div>
    </div>

    <br><h2><%= "#{@dog.name.capitalize}'s reviews"%></h2>
        <%= link_to "REVIEW #{@dog.name.upcase}", new_dog_review_path(@dog), class:"btd-yw" %>

      <% @reviews.each_with_index do |review, i| %>
    <div class="card-rev">
          <div class="user-description">
              <h2>  <% review.rating.round(0).to_i.times do %>
                  <i class="fas fa-star"></i>
              <% end %>
              </h2>
              <h2><%= review[:description] %></h2>
              <h3><%= @authors[i][:name] %> <%= @authors[i][:lastname] %></h3>
          </div>
        </div>
    <% end %>

</div>

app/views/dogs/show.html.erb
<div class="container">
  <br><h1><%=@dog.name.capitalize%>
    <% if @stars %>
      <% @stars.round(0).to_i.times do %>
        <i class="fas fa-star"></i>
      <% end %>
    <% end %>
  </h1>

  <div class="profile-page">

    <div class="card-show">
      <%= cl_image_tag @dog.photo, width: 200, height: 150, crop: :fill %>
      <br>
       <div class="fullspace">
         <%= link_to "BOOK #{@dog.name.upcase}", new_dog_booking_path(@dog), class: "btd-yel-lg" %>
       </div>
      <div class= "profile-grid">

        <div class= "description">
          <h3>Breed:</h3>
          <p><%= @dog[:race] %></p>
          <h3>Size:</h3>
          <p><%= @dog[:size] %></p>
          <h3>Description:</h3>
          <p><%= @dog[:description] %></p>
        </div>

        <div class= "dog-owner">
          <h3>Owner:</h3>
          <p><%= @owner[:name] %> <%= @owner[:lastname] %></p>
          <h3>Contact:</h3>
          <p><%= @owner[:email] %></p>
        </div>

      </div>


    </div>

    <div class= "map-bookings">

      <div class="map">
        <div
        id="map"
        style="width: 100%;
        height: 100%;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
      ></div>
      </div>

      <div class= "bookings">
          <h3><%= "#{@dog.name.capitalize}'s Bookings"%></h3>
          <% @bookings.each do |booking| %>
            <p><%= booking[:date] %></p>
            <p><%= booking[:description] %></p>
            <br>
          <% if policy(booking).show? %>
            <%= link_to 'more details on this booking', booking_path(booking), class: "links-sessions" %>
          <% end %>
          <br>
          <% end %>
      </div>

    </div>

  </div>

  <br><h2><%= "#{@dog.name.capitalize}'s reviews"%></h2>
      <%= link_to "REVIEW #{@dog.name.upcase}", new_dog_review_path(@dog), class:"btd-yw" %>
    <% @reviews.each_with_index do |review, i| %>
  <div class="card-rev">
        <div class="user-description">
            <h2>  <% review.rating.round(0).to_i.times do %>
                <i class="fas fa-star"></i>
            <% end %>
            </h2>
            <h2><%= review[:description] %></h2>
            <h3><%= @authors[i][:name] %> <%= @authors[i][:lastname] %></h3>
        </div>
      </div>
  <% end %>

</div>