config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # a guest can create a user, a user can see his profile and dashboard
  resources :users, only: [:show] do
    member do
      get 'dashboard'
    end
  end
  # all 7 crud action can be done for dogs.
  resources :dogs do
    # a guest can preview a specific dog page before login-in
    member do
      get 'preview'
    end
    # a user can create a new booking
    resources :bookings, only: [:new, :create]
    # can create a review
    resources :reviews, only: [:new, :create]
  end
  # a user can see details of one booking and delete.
  resources :bookings, only: [:show, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :lastname, presence: true
  validates :email, uniqueness: true
  validates :address, presence: true

  has_many :dogs, foreign_key: :owner_id, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  mount_uploader :photo, PhotoUploader
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :dashboard]

  def show
    @dogs = policy_scope(Dog)
    @bookings = policy_scope(Booking)
    # @stars = @dogs.map { |dog| Dog.average_rating(dog) }
    @stars = @dogs.map { |dog| dog.reviews.average(:rating) }
  end

  def dashboard
    # a user can see all of his bookings, but owner will not yet see all the bookings for his dogs
    @bookings = Booking.joins(:dog)

    bookings_owner = BookingPolicy::Scope.new(current_user, @bookings).resolve

    if current_user.owner == true
      @s = bookings_owner.where('dogs.owner': current_user)
    else
      @s = bookings_owner.where(user: current_user)
    end
    # s = @bookings_owner.where(dog: { owner: current_user })
    # TODO: Load the dogs of the user in a variable
    # TODO: Load the booking where dog is in the list of dogs from the owner

    # send an array of all the dogs associated with the bookings to the views
    @dogs = @bookings.map(&:dog)
    # send an array of all the renter associated with the bookings to the views
    @renter = @bookings.map(&:user)
  end

  def set_user
    @user = current_user
    authorize @user
  end
end

app/views/users/dashboard.html.erb
<div class="container">
<br><h1>My Playdates <i class="fas fa-paw"></i> </h1>

<% @s.each_with_index do |booking, i| %>

 <% if policy(booking).show? %>
  <br><div class="card-user-bg">
    <%= cl_image_tag @dogs[i].photo, width: 200, height: 150, crop: :fill %>
      <div class="user-description">
          <h2>Playdate with <%= link_to @dogs[i][:name], dog_path(@dogs[i][:id]), class:"links-sessions" %></h2>
          <h3>When:</h3>
          <p><%= booking[:startdate].strftime("From: %d %B %Y at %Hh%M") %></p>
          <p><%= booking[:enddate].strftime("To: %d %B %Y at %Hh%M") %></p>
          <p><%= booking[:date] %></p>
          <h3>Playdate description:</h3>
          <p><%= booking[:description] %></p>

          <h3><%= booking[:confirmed] ? 'Booking confirmed !' : 'To be confirmed by owner ' + booking.dog.owner.name + booking.dog.owner.lastname %></h3>
        <br><%= link_to "#{@dogs[i][:name].upcase}'S PROFILE", dog_path(@dogs[i][:id]), class:"btd-yel" %>
        <% if policy(booking).destroy? %>
          <%= link_to 'DELETE THIS BOOKING', booking_path(booking), method: :delete,
          data: { confirm: "Are you sure?" }, class:"btd-ind" %>
        <% end %>

         <%= link_to "Renter's profile", user_path(@renter[i][:id]), class:"btd-yel" %>
      </div>

  </div>
  <% end %>
<% end %>
</div>

app/views/users/show.html.erb
<div class="container">
<br><h1>My Profile</h1>
<% if policy(@user).show? %>
   <div class="card-user">
    <%= cl_image_tag @user.photo, crop: :fill, id: "user", gravity: :face %>
      <div class="user-description">
        <h2>
          <%= @user.name %> <%= @user.lastname %>
        </h2>
          <p><%= @user.email %></p>
          <p><%= @user.address %></p>
          <%= link_to 'Add a new dog', new_dog_path, class: "btd-yels" %>
      </div>
    </div>
  <br><br>
  <div class="profile-grid">
    <h3>My Doggies</h3>
    <h3>My Bookings</h3>
  </div>

  <div class="profile-grid">

    <div class="card-user-dogs">
      <div class="cardsf">
        <% @dogs.each_with_index do |dog, i| %>
          <div class="card-dog">
            <%= cl_image_tag dog.photo, width: 200, height: 150, crop: :fill %>

                <% if @stars[i] %>
                  <% @stars[i].round(0).to_i.times do %>
                    <i class="fas fa-star"></i>
                  <% end %>
                <% end %>

            <p><%= link_to dog[:name].upcase, dog_path(dog), class: "links-sessions" %></p>
            <%= link_to "EDIT", edit_dog_path(dog), class:"btd-yels"  %>
            <%= link_to "REMOVE", dog_path(dog),
                method: :delete,
                data: { confirm: "Are you sure you want to delete this dog?" }, class:"btd-yels" %><br><br>
          </div>
        <% end %>
      </div>
    <br></div>



    <div class="card-user-dogs">
      <div class="cardsf">
        <% @bookings.each do |booking| %>
        <div class="card-book">
          <h3> <%=  booking.dog.name.upcase%> <i class="fas fa-paw"></i> </h3>
          <h4> <%= booking[:description] %></h4>
            <p><%= booking.startdate.strftime("From %m/%d/%Y at %H:%I") %>
            <br><%= booking.enddate.strftime("To %m/%d/%Y at %H:%I") %></p>
          <%= link_to 'MORE DETAILS', booking_path(booking), class: "btd-yels" %>
        </div>
        <% end %>
      </div>
    </div>

  </div>

<% end %>
</div>