config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # a guest can create a user, a user can see his profile and dashboard
  resources :users, only: [:show] do
    member do
      get 'dashboard'
    end
  end
  # all 7 crud action can be done for dogs.
  resources :dogs do
    # a guest can preview a specific dog page before login-in
    member do
      get 'preview'
    end
    # a user can create a new booking
    resources :bookings, only: [:new, :create]
    # can create a review
    resources :reviews, only: [:new, :create]
  end
  # a user can see details of one booking and delete.
  resources :bookings, only: [:show, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://www.instagram.com/kabosumama/"><i class="fab fa-instagram"></i></a>
    <a href="https://www.facebook.com/VeryDoge/"><i class="fab fa-facebook"></i></a>
    <a href="https://twitter.com/wowsuchdoge?lang=fr"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    Follow us on social medias <i class="fas fa-paw"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<!-- MUST LATER ADD MESSAGES PATHS IN THE LINKS !!!!! -->

<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path , class: "navbar-brand" do %>
        <%= image_tag "/images/index.png", class: "logo" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <p><%= current_user.lastname %></p>
        <li class="nav-item active">
          <%= link_to "DASHBOARD", dashboard_user_path(current_user), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "MESSAGES", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= cl_image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "PROFILE", user_path(current_user) , class: "dropdown-item" %>
            <%= link_to "LOG OUT", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "LOGIN", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "SIGN UP", '/users/sign_up', class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>